export const countries = [
  { key: 'afghanistan', label: 'Afghanistan', value: '+93' },
  { key: 'albania', label: 'Albania', value: '+355' },
  { key: 'algeria', label: 'Algeria', value: '+213' },
  { key: 'andorra', label: 'Andorra', value: '+376' },
  { key: 'angola', label: 'Angola', value: '+244' },
  { key: 'anguilla', label: 'Anguilla', value: '+1-264' },
  { key: 'antigua_and_barbuda', label: 'Antigua and Barbuda', value: '+1-268' },
  { key: 'argentina', label: 'Argentina', value: '+54' },
  { key: 'armenia', label: 'Armenia', value: '+374' },
  { key: 'australia', label: 'Australia', value: '+61' },
  { key: 'austria', label: 'Austria', value: '+43' },
  { key: 'azerbaijan', label: 'Azerbaijan', value: '+994' },
  { key: 'bahamas', label: 'Bahamas', value: '+1-242' },
  { key: 'bahrain', label: 'Bahrain', value: '+973' },
  { key: 'bangladesh', label: 'Bangladesh', value: '+880' },
  { key: 'barbados', label: 'Barbados', value: '+1-246' },
  { key: 'belarus', label: 'Belarus', value: '+375' },
  { key: 'belgium', label: 'Belgium', value: '+32' },
  { key: 'belize', label: 'Belize', value: '+501' },
  { key: 'benin', label: 'Benin', value: '+229' },
  { key: 'bhutan', label: 'Bhutan', value: '+975' },
  { key: 'bolivia', label: 'Bolivia', value: '+591' },
  {
    key: 'bosnia_and_herzegovina',
    label: 'Bosnia and Herzegovina',
    value: '+387',
  },
  { key: 'botswana', label: 'Botswana', value: '+267' },
  { key: 'brazil', label: 'Brazil', value: '+55' },
  { key: 'brunei', label: 'Brunei', value: '+673' },
  { key: 'bulgaria', label: 'Bulgaria', value: '+359' },
  { key: 'burkina_faso', label: 'Burkina Faso', value: '+226' },
  { key: 'burundi', label: 'Burundi', value: '+257' },
  { key: 'cabo_verde', label: 'Cabo Verde', value: '+238' },
  { key: 'cambodia', label: 'Cambodia', value: '+855' },
  { key: 'cameroon', label: 'Cameroon', value: '+237' },
  { key: 'canada', label: 'Canada', value: '+1' },
  {
    key: 'central_african_republic',
    label: 'Central African Republic',
    value: '+236',
  },
  { key: 'chad', label: 'Chad', value: '+235' },
  { key: 'chile', label: 'Chile', value: '+56' },
  { key: 'china', label: 'China', value: '+86' },
  { key: 'colombia', label: 'Colombia', value: '+57' },
  { key: 'comoros', label: 'Comoros', value: '+269' },
  { key: 'congo', label: 'Congo', value: '+242' },
  { key: 'congo_drc', label: 'Congo, DRC', value: '+243' },
  { key: 'costa_rica', label: 'Costa Rica', value: '+506' },
  { key: 'croatia', label: 'Croatia', value: '+385' },
  { key: 'cuba', label: 'Cuba', value: '+53' },
  { key: 'cyprus', label: 'Cyprus', value: '+357' },
  { key: 'czech_republic', label: 'Czech Republic', value: '+420' },
  { key: 'denmark', label: 'Denmark', value: '+45' },
  { key: 'djibouti', label: 'Djibouti', value: '+253' },
  { key: 'dominica', label: 'Dominica', value: '+1-767' },
  { key: 'dominican_republic', label: 'Dominican Republic', value: '+1-809' },
  { key: 'ecuador', label: 'Ecuador', value: '+593' },
  { key: 'egypt', label: 'Egypt', value: '+20' },
  { key: 'el_salvador', label: 'El Salvador', value: '+503' },
  { key: 'equatorial_guinea', label: 'Equatorial Guinea', value: '+240' },
  { key: 'eritrea', label: 'Eritrea', value: '+291' },
  { key: 'estonia', label: 'Estonia', value: '+372' },
  { key: 'eswatini', label: 'Eswatini', value: '+268' },
  { key: 'ethiopia', label: 'Ethiopia', value: '+251' },
  { key: 'fiji', label: 'Fiji', value: '+679' },
  { key: 'finland', label: 'Finland', value: '+358' },
  { key: 'france', label: 'France', value: '+33' },
  { key: 'gabon', label: 'Gabon', value: '+241' },
  { key: 'gambia', label: 'Gambia', value: '+220' },
  { key: 'georgia', label: 'Georgia', value: '+995' },
  { key: 'germany', label: 'Germany', value: '+49' },
  { key: 'ghana', label: 'Ghana', value: '+233' },
  { key: 'greece', label: 'Greece', value: '+30' },
  { key: 'grenada', label: 'Grenada', value: '+1-473' },
  { key: 'guatemala', label: 'Guatemala', value: '+502' },
  { key: 'guinea', label: 'Guinea', value: '+224' },
  { key: 'guinea_bissau', label: 'Guinea-Bissau', value: '+245' },
  { key: 'guyana', label: 'Guyana', value: '+592' },
  { key: 'haiti', label: 'Haiti', value: '+509' },
  { key: 'honduras', label: 'Honduras', value: '+504' },
  { key: 'hungary', label: 'Hungary', value: '+36' },
  { key: 'iceland', label: 'Iceland', value: '+354' },
  { key: 'india', label: 'India', value: '+91' },
  { key: 'indonesia', label: 'Indonesia', value: '+62' },
  { key: 'iran', label: 'Iran', value: '+98' },
  { key: 'iraq', label: 'Iraq', value: '+964' },
  { key: 'ireland', label: 'Ireland', value: '+353' },
  { key: 'israel', label: 'Israel', value: '+972' },
  { key: 'italy', label: 'Italy', value: '+39' },
  { key: 'jamaica', label: 'Jamaica', value: '+1-876' },
  { key: 'japan', label: 'Japan', value: '+81' },
  { key: 'jordan', label: 'Jordan', value: '+962' },
  { key: 'kazakhstan', label: 'Kazakhstan', value: '+7' },
  { key: 'kenya', label: 'Kenya', value: '+254' },
  { key: 'kiribati', label: 'Kiribati', value: '+686' },
  { key: 'korea_north', label: 'North Korea', value: '+850' },
  { key: 'korea_south', label: 'South Korea', value: '+82' },
  { key: 'kosovo', label: 'Kosovo', value: '+383' },
  { key: 'kuwait', label: 'Kuwait', value: '+965' },
  { key: 'kyrgyzstan', label: 'Kyrgyzstan', value: '+996' },
  { key: 'laos', label: 'Laos', value: '+856' },
  { key: 'latvia', label: 'Latvia', value: '+371' },
  { key: 'lebanon', label: 'Lebanon', value: '+961' },
  { key: 'lesotho', label: 'Lesotho', value: '+266' },
  { key: 'liberia', label: 'Liberia', value: '+231' },
  { key: 'libya', label: 'Libya', value: '+218' },
  { key: 'liechtenstein', label: 'Liechtenstein', value: '+423' },
  { key: 'lithuania', label: 'Lithuania', value: '+370' },
  { key: 'luxembourg', label: 'Luxembourg', value: '+352' },
  { key: 'madagascar', label: 'Madagascar', value: '+261' },
  { key: 'malawi', label: 'Malawi', value: '+265' },
  { key: 'malaysia', label: 'Malaysia', value: '+60' },
  { key: 'maldives', label: 'Maldives', value: '+960' },
  { key: 'mali', label: 'Mali', value: '+223' },
  { key: 'malta', label: 'Malta', value: '+356' },
  { key: 'marshall_islands', label: 'Marshall Islands', value: '+692' },
  { key: 'mauritania', label: 'Mauritania', value: '+222' },
  { key: 'mauritius', label: 'Mauritius', value: '+230' },
  { key: 'mexico', label: 'Mexico', value: '+52' },
  { key: 'micronesia', label: 'Micronesia', value: '+691' },
  { key: 'moldova', label: 'Moldova', value: '+373' },
  { key: 'monaco', label: 'Monaco', value: '+377' },
  { key: 'mongolia', label: 'Mongolia', value: '+976' },
  { key: 'montenegro', label: 'Montenegro', value: '+382' },
  { key: 'morocco', label: 'Morocco', value: '+212' },
  { key: 'mozambique', label: 'Mozambique', value: '+258' },
  { key: 'myanmar', label: 'Myanmar', value: '+95' },
  { key: 'namibia', label: 'Namibia', value: '+264' },
  { key: 'nauru', label: 'Nauru', value: '+674' },
  { key: 'nepal', label: 'Nepal', value: '+977' },
  { key: 'netherlands', label: 'Netherlands', value: '+31' },
  { key: 'new_zealand', label: 'New Zealand', value: '+64' },
  { key: 'nicaragua', label: 'Nicaragua', value: '+505' },
  { key: 'niger', label: 'Niger', value: '+227' },
  { key: 'nigeria', label: 'Nigeria', value: '+234' },
  { key: 'niue', label: 'Niue', value: '+683' },
  { key: 'norfolk_island', label: 'Norfolk Island', value: '+672' },
  { key: 'north_macedonia', label: 'North Macedonia', value: '+389' },
  { key: 'norway', label: 'Norway', value: '+47' },
  { key: 'oman', label: 'Oman', value: '+968' },
  { key: 'pakistan', label: 'Pakistan', value: '+92' },
  { key: 'palau', label: 'Palau', value: '+680' },
  { key: 'palestine', label: 'Palestine', value: '+970' },
  { key: 'panama', label: 'Panama', value: '+507' },
  { key: 'papua_new_guinea', label: 'Papua New Guinea', value: '+675' },
  { key: 'paraguay', label: 'Paraguay', value: '+595' },
  { key: 'peru', label: 'Peru', value: '+51' },
  { key: 'philippines', label: 'Philippines', value: '+63' },
  { key: 'poland', label: 'Poland', value: '+48' },
  { key: 'portugal', label: 'Portugal', value: '+351' },
  { key: 'qatar', label: 'Qatar', value: '+974' },
  { key: 'romania', label: 'Romania', value: '+40' },
  { key: 'russia', label: 'Russia', value: '+7' },
  { key: 'rwanda', label: 'Rwanda', value: '+250' },
  {
    key: 'saint_kitts_and_nevis',
    label: 'Saint Kitts and Nevis',
    value: '+1-869',
  },
  { key: 'saint_lucia', label: 'Saint Lucia', value: '+1-758' },
  {
    key: 'saint_vincent_and_the_grenadines',
    label: 'Saint Vincent and the Grenadines',
    value: '+1-784',
  },
  { key: 'samoa', label: 'Samoa', value: '+685' },
  { key: 'san_marino', label: 'San Marino', value: '+378' },
  {
    key: 'sao_tome_and_principe',
    label: 'Sao Tome and Principe',
    value: '+239',
  },
  { key: 'saudi_arabia', label: 'Saudi Arabia', value: '+966' },
  { key: 'senegal', label: 'Senegal', value: '+221' },
  { key: 'serbia', label: 'Serbia', value: '+381' },
  { key: 'seychelles', label: 'Seychelles', value: '+248' },
  { key: 'sierra_leone', label: 'Sierra Leone', value: '+232' },
  { key: 'singapore', label: 'Singapore', value: '+65' },
  { key: 'sint_maarten', label: 'Sint Maarten', value: '+1-721' },
  { key: 'slovakia', label: 'Slovakia', value: '+421' },
  { key: 'slovenia', label: 'Slovenia', value: '+386' },
  { key: 'solomon_islands', label: 'Solomon Islands', value: '+677' },
  { key: 'somalia', label: 'Somalia', value: '+252' },
  { key: 'south_africa', label: 'South Africa', value: '+27' },
  { key: 'south_sudan', label: 'South Sudan', value: '+211' },
  { key: 'spain', label: 'Spain', value: '+34' },
  { key: 'sri_lanka', label: 'Sri Lanka', value: '+94' },
  { key: 'state_of_palestine', label: 'State of Palestine', value: '+970' },
  { key: 'sudan', label: 'Sudan', value: '+249' },
  { key: 'suriname', label: 'Suriname', value: '+597' },
  { key: 'sweden', label: 'Sweden', value: '+46' },
  { key: 'switzerland', label: 'Switzerland', value: '+41' },
  { key: 'syria', label: 'Syria', value: '+963' },
  { key: 'taiwan', label: 'Taiwan', value: '+886' },
  { key: 'tajikistan', label: 'Tajikistan', value: '+992' },
  { key: 'tanzania', label: 'Tanzania', value: '+255' },
  { key: 'thailand', label: 'Thailand', value: '+66' },
  { key: 'timor_leste', label: 'Timor-Leste', value: '+670' },
  { key: 'togo', label: 'Togo', value: '+228' },
  { key: 'tonga', label: 'Tonga', value: '+676' },
  { key: 'trinidad_and_tobago', label: 'Trinidad and Tobago', value: '+1-868' },
  { key: 'tunisia', label: 'Tunisia', value: '+216' },
  { key: 'turkey', label: 'Turkey', value: '+90' },
  { key: 'turkmenistan', label: 'Turkmenistan', value: '+993' },
  { key: 'tuvalu', label: 'Tuvalu', value: '+688' },
  { key: 'uganda', label: 'Uganda', value: '+256' },
  { key: 'ukraine', label: 'Ukraine', value: '+380' },
  { key: 'united_arab_emirates', label: 'United Arab Emirates', value: '+971' },
  { key: 'united_kingdom', label: 'United Kingdom', value: '+44' },
  { key: 'united_states', label: 'United States', value: '+1' },
  { key: 'uruguay', label: 'Uruguay', value: '+598' },
  { key: 'uzbekistan', label: 'Uzbekistan', value: '+998' },
  { key: 'vanuatu', label: 'Vanuatu', value: '+678' },
  { key: 'venezuela', label: 'Venezuela', value: '+58' },
  { key: 'vietnam', label: 'Vietnam', value: '+84' },
  { key: 'yemen', label: 'Yemen', value: '+967' },
  { key: 'zambia', label: 'Zambia', value: '+260' },
  { key: 'zimbabwe', label: 'Zimbabwe', value: '+263' },
];
